TEAM_REGISTRY = {
    "Arsenal": ("ARS", "Arsenal"),
    "Aston Villa": ("AVL", "Aston Villa"),
    "Bournemouth": ("BOU", "AFC Bournemouth"),
    "Brentford": ("BRE", "Brentford"),
    "Brighton": ("BRI", "Brighton & Hove Albion"),
    "Burnley": ("BUR", "Burnley"),
    "Cardiff": ("CAR", "Cardiff City"),
    "Chelsea": ("CHE", "Chelsea"),
    "Crystal Palace": ("CRY", "Crystal Palace"),
    "Everton": ("EVE", "Everton"),
    "Fulham": ("FUL", "Fulham"),
    "Huddersfield": ("HUD", "Huddersfield Town"),
    "Hull": ("HUL", "Hull City"),
    "Ipswich": ("IPS", "Ipswich Town"),
    "Leeds": ("LEE", "Leeds United"),
    "Leicester": ("LEI", "Leicester City"),
    "Liverpool": ("LIV", "Liverpool"),
    "Luton": ("LUT", "Luton Town"),
    "Man City": ("MCI", "Manchester City"),
    "Man United": ("MUN", "Manchester United"),
    "Middlesbrough": ("MID", "Middlesbrough"),
    "Newcastle": ("NEW", "Newcastle United"),
    "Norwich": ("NOR", "Norwich City"),
    "Nott'm Forest": ("NFO", "Nottingham Forest"),
    "Sheffield United": ("SHU", "Sheffield United"),
    "Southampton": ("SOU", "Southampton"),
    "Stoke": ("STK", "Stoke City"),
    "Sunderland": ("SUN", "Sunderland"),
    "Swansea": ("SWA", "Swansea City"),
    "Tottenham": ("TOT", "Tottenham Hotspur"),
    "Watford": ("WAT", "Watford"),
    "West Brom": ("WBA", "West Bromwich Albion"),
    "West Ham": ("WHU", "West Ham United"),
    "Wolves": ("WOL", "Wolverhampton Wanderers"),
}
